####################################
# Upload library and data
####################################

knitr::opts_chunk$set(echo = TRUE)
set.seed(2024)

library(mstate)
library(survival)
library(dplyr)
library(survminer)
library(flexsurv)

all_data <- load("simulation5K_MM_oneseed.RData")
data <- dataset[[1]]  #we upload the datasets generated by first seed over 5 different observation schemes


################################################################
# Fitting a parametric model for each transition over EO dataset
################################################################
EO_data <- data[[1]]


tmat <- mstate::transMat(x = list(c(2, 3),c(3),c()), names = c("Dementia-free","Dementia", "Death")) 

data_long_EO <- msprep(data = EO_data, trans = tmat, 
                    time = c(NA, "onset_age", "death_time"), 
                    status = c(NA, "onset", "dead"), 
                    keep = c("age","cov1", "cov2", "cov3"),
                    id="patient_id")

data_long_EO$Tstart[data_long_EO$trans<3] <- data_long_EO$Tstart[data_long_EO$trans<3] +data_long_EO$age[data_long_EO$trans<3]

data_long_EO$time <- data_long_EO$Tstop-data_long_EO$Tstart

n_trans <- max(tmat, na.rm = TRUE)
fits_wei_EO <- vector(mode = "list", length = n_trans)
aic_values_EO <- numeric()
for (i in 1:3){
  fits_wei_EO[[i]] <- flexsurvreg(Surv(Tstart, Tstop, status) ~ cov1+cov2+cov3,  
                               data = subset(data_long_EO, trans == i),
                               dist = "gompertz")
}

par(mfrow=c(2,2))
plot(fits_wei_EO[[1]],type="cumhaz", xlim=c(60,102))
plot(fits_wei_EO[[2]],type="cumhaz", xlim=c(60,102))
plot(fits_wei_EO[[3]],type="cumhaz", xlim=c(75,100))
title(main = " Model per transition over EO Dataset", outer = TRUE, line = -1)


for (i in 1:3){
  print(fits_wei_EO[[i]])
  aic_values_EO[i] <- AIC(fits_wei_EO[[i]])
}

params_EO <- matrix(0, nrow = n_trans, ncol = 5)
param_names <- names(fits_wei_EO[[1]]$coefficients)
colnames(params_EO) <- param_names

for (i in 1:3){
  for (j in 1:5){
    params_EO[i,j] <- fits_wei_EO[[i]] $coefficients[j]
  }
}
  
aic_table_EO <- data.frame(
  Model = c("Transition 1", "Transition 2", "Transition 3"),
  AIC = aic_values_EO
)



#######################################################################################################
# Fitting a parametric model for each transition over scheme A, wrongly using observation as it were EO
#######################################################################################################

schemeA_data <- data[[3]]
for (i in 1:500){
  if(any(schemeA_data$onset[schemeA_data$patient_id==i]==1))
    schemeA_data$onset[schemeA_data$patient_id==i] <- 1
}
schemeA_data <- schemeA_data[,1:9]
schemeA_data <- schemeA_data %>%
  group_by(patient_id) %>%
  slice(1) %>%
  ungroup()

data_long_wrong <- msprep(data = schemeA_data, trans = tmat,
                    time = c(NA, "onset_age", "death_time"),
                    status = c(NA, "onset", "dead"),
                    keep = c("age","cov1", "cov2", "cov3"),
                    id="patient_id")

data_long_wrong$Tstart[data_long_wrong$trans<3] <- data_long_wrong$Tstart[data_long_wrong$trans<3] +data_long_wrong$age[data_long_wrong$trans<3]
data_long_wrong$time <- data_long_wrong$Tstop-data_long_wrong$Tstart

n_trans <- max(tmat, na.rm = TRUE)
fits_wei_wrong <- vector(mode = "list", length = n_trans)
aic_values_wrong <- numeric()
for (i in 1:3){
  fits_wei_wrong[[i]] <- flexsurvreg(Surv(Tstart, Tstop, status) ~ cov1+cov2+cov3,  
                               data = subset(data_long_wrong, trans == i),
                               dist = "gompertz")}

par(mfrow=c(2,2))
plot(fits_wei_wrong[[1]],type="cumhaz", xlim=c(60,102))
plot(fits_wei_wrong[[2]],type="cumhaz", xlim=c(60,102))
plot(fits_wei_wrong[[3]],type="cumhaz", xlim=c(75,100))

for (i in 1:3){
  print(fits_wei_wrong[[i]])
  aic_values_wrong[i] <- AIC(fits_wei_wrong[[i]])
}

aic_table_wrong <- data.frame(
  Model = c("Transition 1", "Transition 2", "Transition 3"),
  AIC = aic_values_wrong
)

################################################
# Fitting a model with msm over panel data
################################################

schemeA_visits <- data[[3]]
schemeA_visits$state <- 1

update_state <- function(df) {
  df <- df %>%
    group_by(patient_id) %>%
    mutate(
      state = ifelse(onset == 1, 2, state),
      state = ifelse(row_number() == n() & dead == 1, 3, state)
    ) %>%
    ungroup() 
  
  return(df)
}

schemeA_visits <- update_state(schemeA_visits)

statetable.msm(state, patient_id, data=schemeA_visits)
Q <- rbind(c(0, 0.5, 0.5),
           c(0, 0, 1),
           c(0, 0, 0)) 

model.msm <- msm(state ~ age,
                subject = patient_id,
                data = schemeA_visits, 
                qmatrix = Q,
                covariates = ~ cov1 + cov2 + cov3,
                gen.inits=TRUE,
                control = list(fnscale = 1000))

sojourn.msm(model.msm)

AIC(model.msm)

pmatrix.msm(model.msm, t=10)

################################################
# Impute dataset of patients observed every year
################################################

schemeA_visits <- data[[2]]
schemeA_data <- data[[2]]

for (i in 1:500){
  if(any(schemeA_data$onset[schemeA_data$patient_id==i]==1))
    schemeA_data$onset[schemeA_data$patient_id==i] <- 1
}
schemeA_data <- schemeA_data[,1:9]
schemeA_data <- schemeA_data %>%
  group_by(patient_id) %>%
  slice(1) %>%
  ungroup()

n<-length(unique(schemeA_data$patient_id))  # number of patients
m<-30             # number of imputation
nIter<-10            # number of iterations
eps<-0.01             # criteria of convergence
nx1<-3                # number of variables in onset model
nx2<-4                # number of variables in proportional hazards death model (include DISEASE variable)


# =================================================
# Initial estimate of hazard of developing dementia
# =================================================
# we fit a cox model for the development of dementia setting start as age of the enter in
# the study and onset_age as the middle point between beginning of the study and when onset is observed
# for those developing dementia and censored time if not observed

temp <- schemeA_data
temp$midage <- (schemeA_data$age + schemeA_data$onset_age)/2
temp$onset_age <- (temp$onset)*temp$midage + (1-temp$onset)*temp$onset_age
mod_onset <- coxph(Surv(age,onset_age,onset)~cov1+cov2+cov3, data = temp)
onsethaz<-basehaz(mod_onset,center=FALSE) 
onsetpar<-mod_onset$coefficients


# ====================================
# Initial estimate of hazards of dying 
# ====================================
# we fit a cox model for survival to death distinguishing between those having dementia and those dementia-free
# for both we set the right extreme of the interval at censoring time/ death and time start at midage
# for those having dementia and beginning of the study for the latter
# extra covariate: onset, the presence of dementia is likely tho change the outcome

temp$start<-(temp$onset==1)*temp$midage+(temp$onset==0)*temp$age
mod_death<- coxph(Surv(start,death_time,dead)~cov1+cov2+cov3+onset, data = temp)
deathhaz<-basehaz(mod_death,center=FALSE)
deathpar<-mod_death$coefficients

# ==========================
# plots of survival curves
# ==========================

par(mfrow=c(2,2))

surv_fit_onset <- survfit(mod_onset)
ggsurv_onset <- ggsurvplot(surv_fit_onset, data = temp,
                           conf.int = TRUE,        
                           pval = TRUE,            
                           risk.table = TRUE,      
                           ggtheme = theme_minimal())  


print(ggsurv_onset)

surv_fit_death <- survfit(mod_death)
plot(surv_fit_death)
ggsurv_death <- ggsurvplot(surv_fit_death, data = temp,
                     conf.int = TRUE,        
                     pval = TRUE,            
                     risk.table = TRUE,      
                     ggtheme = theme_minimal())  


print(ggsurv_death)

aic_onset <- AIC(mod_onset)
aic_death <- AIC(mod_death)

aic_table_cox_initial <- data.frame(
  Model = c("Onset Model", "Death Model"),
  AIC = c(aic_onset, aic_death)
)

# =========================================
# Imputation of onset status and onset age
# =========================================
pb <- txtProgressBar(min = 0, max = nIter, style = 3)

for (k in 1:(nIter)){
  # hazards computation
  tzero<-data.frame(matrix(0,1,2))
  names(tzero)<-c("time","hazard")
  onsethaz<-rbind(tzero,onsethaz) 
  onsethaz$h<-onsethaz$hazard
  onsethaz$h[nrow(onsethaz)]<-NA
  for (i in 1:(nrow(onsethaz)-1))
    onsethaz$h[i]<-(onsethaz$hazard[i+1]-onsethaz$hazard[i])/(onsethaz$time[i+1]-onsethaz$time[i])
  
  deathhaz<-rbind(tzero,deathhaz)
  deathhaz$h<-deathhaz$hazard
  deathhaz$h[nrow(deathhaz)]<-NA
  for (i in 1:(nrow(deathhaz)-1))
    deathhaz$h[i]<-(deathhaz$hazard[i+1]-deathhaz$hazard[i])/(deathhaz$time[i+1]-deathhaz$time[i])
  remove(tzero)
  
  # if ((k==1) | (k==nIter)) {
  #   onsethaz$S<-exp(-onsethaz$hazard) #survival function onset model (baseline)
  #   plot(onsethaz$time, onsethaz$h, xlab='Time', ylim=c(0,0.4),ylab='Hazard function', main='Dementia incidence rate')
  #   plot(onsethaz$time, onsethaz$S, xlab='Time', ylim=c(0,1.0),ylab='Baseline survival function', main='Probability of not having dementia')
  #   onsethaz$S<-NULL
  #   
  #   deathhaz$S<-exp(-deathhaz$hazard) # survival function death model (baseline)
  #   plot(deathhaz$time, deathhaz$h, xlab='Time', ylim=c(0,0.6), ylab='Hazard function', main='Mortality rate')
  #   plot(deathhaz$time, deathhaz$S, xlab='Time', ylim=c(0,1), ylab='Baseline survival function', main='Survival rate')
  #   deathhaz$S<-NULL
  # }
 
  combhaz<-merge(onsethaz,deathhaz,by.x="time", by.y="time",all.x=TRUE, all.y=TRUE, suffixes = c(".12",".13"))
  #merging hazards from both models, since they are computed on different transition times we might have NA values
  if (is.na(combhaz$hazard.12[1])) combhaz$hazard.12[1]<-0
  if (is.na(combhaz$hazard.13[1])) combhaz$hazard.13[1]<-0
  
  #avoiding NA
  for (i in 2: nrow(combhaz))
  {
    if (is.na(combhaz$h.12[i]))
    {
      combhaz$h.12[i]<-combhaz$h.12[i-1]
      combhaz$hazard.12[i]<-combhaz$hazard.12[i-1]+combhaz$h.12[i-1]*(combhaz$time[i]-combhaz$time[i-1])
    }
    if (is.na(combhaz$h.13[i]))
    {
      combhaz$h.13[i]<-combhaz$h.13[i-1]
      combhaz$hazard.13[i]<-combhaz$hazard.13[i-1]+combhaz$h.13[i-1]*(combhaz$time[i]-combhaz$time[i-1])
    }
  }
  
  demstatus<-matrix(nrow=nrow(schemeA_data),ncol=m,rep(schemeA_data$onset,m))
  # matrix representing dementia status for each patient for each imputated dataset (set to 1 if dementia observed in original dataset)
  dementage<-matrix(nrow=nrow(schemeA_data),ncol=m,0)
  # matrix representing dementia onset age for each patient for each imputated dataset (in this case is censored in orignal dataset, so set to zero for everyone)
  c1<-matrix(nrow=nrow(schemeA_data),ncol=m,runif(nrow(schemeA_data)*m)) # matrix patients* n_imputed_datasets filled of numbers sampled in [0,1]
  c2<-matrix(nrow=nrow(schemeA_data),ncol=m,runif(nrow(schemeA_data)*m))
  covar<-as.matrix(schemeA_data[,c("cov1","cov2", "cov3")]) #covariates values for each patient
  lp.12<-covar %*% as.vector(t(onsetpar[c("cov1","cov2", "cov3")])) #covariates* theirs estimated coefficients of dementia onset model
  lp.13<-covar %*% as.vector(t(deathpar[c("cov1","cov2", "cov3")]))  #covariates* theirs estimated coefficients of death model
  delta<-deathpar["onset"]
  
  
 
  
  for (i in 1:nrow(schemeA_data)){
    time<-combhaz$time
    S1<-exp(-combhaz$hazard.12*exp(lp.12[i])-combhaz$hazard.13*exp(lp.13[i])) #survival function for living dementia free
    S2<-exp(-combhaz$hazard.13*exp(lp.13[i]+delta)) #survival function for living
    p<-S1*combhaz$h.12/S2 # instantaneous probability of transitioning to dementia conditional on survival upon that time
    
    P<-p   
    P[1]<-0 #P is gonna be cumulative probability of developing dementia over time
    for (j in 2:length(P)) P[j]<-min(1.0,P[j-1]+p[j-1]*(time[j]-time[j-1]))
    F<-data.frame(cbind(time,S1,S2,p,P))
    # names(F)<-c("time","S1","S2","p","P")
    remove(time,S1,S2,p,P)
    
    patient_data <- schemeA_visits[schemeA_visits$patient_id==i,]
    
    #generate onset time for those having dementia observed
    
    if (any(patient_data$onset==1)){
      index <-which(patient_data$onset==1)[1] #first visit observing dementia
      a <- patient_data$age[index-1]
      b <- patient_data$age[index]
      F<-F[F$time>a & F$time<b,]
      nF<-nrow(F) 
      
      if (nF>0) # if there are observation times in that interval
      {    
        minP<-F$P[1]
        maxP<-F$P[nF] 
        if (minP<maxP) #if the probability of transitioning increases over the interval
        {
          F$q<-(F$P-minP)/(maxP-minP)  #normalized probabilities
          for (j in 1:m) dementage[i,j]<-max(F[F$q<=c1[i,j],]$time) #onset is set at maximum time for which probabiltiy is less of
          #a chose treshold sampled from a uniform
        }
        if (minP>=maxP)
          dementage[i,]<-(a+b)/2
      }
      if (nF<=0) #if no observation times are available we set onset in the middle point
        dementage[i,]<-(a+b)/2
    }
    
    #generate onset value and onset time for censored patients
    if (!any(patient_data$onset==1)) {
      n_visits <- length(patient_data$visits)
      a<-patient_data$age[n_visits]
      b<-patient_data$death_time[1]
      d<-patient_data$dead[1]
      F<-F[F$time>a & F$time<b,] #the onset time is restricted to interval (last visit, death/censoring time)
      nF<-nrow(F)
      
      if (nF>0)# if there are observation times in that interval
      {     
        minP<-F$P[1]     
        maxP<-F$P[nF]
        maxt<-F$time[nF]
        S2t<-F$S2[nF] #survival prob of not dying at maximum timepoint in a,b
        S1t<-F$S1[nF] #surival prob of not developing dementia at maximum timepoint in a,b
        S2h23P<-S2t*exp(lp.13[i]+d*delta)*(maxP-minP) #adjust survival probability (extra weight given to disease if patients die) ??
        pD<-S2h23P/(S1t+S2h23P)    # probability of dementia onset during the interval, given survival without dementia up to the final time point  
        
        if (minP<maxP) F$q<-(F$P-minP)/(maxP-minP)  #normalized cum probabilities of developing dementia, needed to set onset-age
        if (minP>=maxP) F$q<-0
      }
      if (nF<=0) pD<-(a<b)*mean(schemeA_data$onset)# if there are observation times in that interval probability of dementia onset 
      #set as the proportion of observed demented people
      
      for (j in 1:m) #creating m imputated datasets
      {
        if (c2[i,j]<=pD) #if  probability of dementia onset is more than a threshold dementia status=1
          # and onset age computed as before: at maximum time for which cum probability of dementia is less of
          #a chosen threshold sampled from a uniform or in middle point
        {
          demstatus[i,j]<-1 
          if (nF>0) dementage[i,j]<-max(F[F$q<=c1[i,j],]$time)
          if (nF<=0) dementage[i,j]<-(a+b)/2
        }
        if (c2[i,j]>pD) #if  probability of dementia onset is less than a threshold dementia status=0
        {
          demstatus[i,j]<-0
          dementage[i,j]<-patient_data$onset_age[1] # we set onset_age at the censoring value
          
          
          
        }
      }
    }
  }
  
  
  # Fit the multi-state model for multiply-imputed data
  
  B1<-matrix(nrow=m, ncol=nx1, 0)
  colnames(B1)<-c("cov1","cov2", "cov3")
  V1<-matrix(nrow=nx1, ncol=nx1, 0)
  H1<-NULL
  
  B2<-matrix(nrow=m, ncol=nx2, 0)
  colnames(B2)<-c("cov1","cov2", "cov3","onset")
  V2<-matrix(nrow=nx2, ncol=nx2, 0)
  H2<-NULL
  
  
  
  for (j in 1:m)
  { 
    temp <- schemeA_data
    temp$demstatus<-demstatus[,j]
    temp$dementage<-dementage[,j]
    mod_onset <- coxph(Surv(age,dementage,demstatus)~cov1+cov2+cov3, data = temp)
    B1[j,]<-mod_onset$coefficients
    V1<-V1+mod_onset$var
    bH<-basehaz(mod_onset,center=FALSE)
    names(bH)<-c(paste("hazard",j,sep=""),"time")
    if (j==1) H1<-bH
    if (j>1) H1<-merge(H1,bH,by="time",all=TRUE)  #H1 contains in each col j hazards for first model fitted over data in dataset j
    
    
    temp$start<-(temp$onset==1)*temp$dementage+(temp$onset==0)*temp$age
    mod_death<- coxph(Surv(start,death_time,dead)~cov1+cov2+cov3+onset, data = temp)
    B2[j,]<-mod_death$coefficients
    V2<-V2+mod_death$var
    
    bHd<-basehaz(mod_death,center=FALSE)
    names(bHd)<-c(paste("hazard",j,sep=""),"time")
    bHd$time<-round(bHd$time,1)
    if (j==1) H2<-bH
    if (j>1) H2<-merge(H2,bH,by="time",all=TRUE)
    
    temp$demstatus<-NULL
    temp$dementage<-NULL
   
  }
  
  
  # performs linear interpolation to fill in missing values in hazard values for m datasets
  for (j in 1:m)
  {
    if (is.na(H1[1,j+1])) H1[1,j+1]<-0
    Htm1<-H1[1,j+1]
    tm1<-H1[1,1]
    im1<-1
    for (i in 2:nrow(H1))
    {
      if (!is.na(H1[i,j+1]))
      {
        if ((i-im1)>1)
          H1[(im1+1):(i-1),j+1]<-Htm1+(H1[i,j+1]-Htm1)/(H1[i,1]-tm1)*(H1[(im1+1):(i-1),1]-tm1) 
        Htm1<-H1[i,j+1]
        tm1<-H1[i,1]
        im1<-i
      }
    }
  }
  
  
  for (j in 1:m)
  {
    if (is.na(H2[1,j+1])) H2[1,j+1]<-0
    Htm1<-H2[1,j+1]
    tm1<-H2[1,1]
    im1<-1
    for (i in 2:nrow(H2))
    {
      if (!is.na(H2[i,j+1]))
      {
        if ((i-im1)>1)
          H2[(im1+1):(i-1),j+1]<-Htm1+(H2[i,j+1]-Htm1)/(H2[i,1]-tm1)*(H2[(im1+1):(i-1),1]-tm1) 
        Htm1<-H2[i,j+1]
        tm1<-H2[i,1]
        im1<-i
      }
    }
  }
  
  
  #calculates the mean hazard values across columns for each row
  onsethaz<-data.frame(cbind(H1[,1],rowMeans(H1[,c(2:(m+1))],na.rm=TRUE)))
  names(onsethaz)<-c("time","hazard")
  #onsethaz<-subset(onsethaz, round(time,1)==time)
  
  #calculates the mean hazard values across columns for each row  
  deathhaz<-data.frame(cbind(H2[,1],rowMeans(H2[,c(2:(m+1))],na.rm=TRUE)))
  names(deathhaz)<-c("time","hazard")
  #deathhaz<-subset(deathhaz, round(time,1)==time)
  remove(H1,H2)
  
  B1<-data.frame(B1)
  V1<-V1/m+(1+1/m)*var(B1)
  onsetpar<-colMeans(B1) 
  
  #a matrix initialized to store results related to the onset model.
  onsetout<-matrix(ncol=5, nrow=nx1,0)
  rownames(onsetout)<-names(onsetpar)
  colnames(onsetout)<-c("coef","exp(coef)","se(coef)","z","p")
  onsetout[,1]<-onsetpar
  onsetout[,2]<-exp(onsetout[,1])
  onsetout[,3]<-sqrt(diag(V1))
  onsetout[,4]<-onsetout[,1]/onsetout[,3]
  onsetout[,5]<-2*(1-pnorm(abs(onsetout[,4])))
  
  B2<-data.frame(B2)
  V2<-V2/m+(1+1/m)*var(B2)
  deathpar<-colMeans(B2) 
  
  #a matrix initialized to store results related to the death model.
  deathout<-matrix(ncol=5, nrow=nx2,0)
  rownames(deathout)<-names(deathpar)
  colnames(deathout)<-c("coef","exp(coef)","se(coef)","z","p")
  deathout[,1]<-deathpar
  deathout[,2]<-exp(deathout[,1])
  deathout[,3]<-sqrt(diag(V2))
  deathout[,4]<-deathout[,1]/deathout[,3]
  deathout[,5]<-2*(1-pnorm(abs(deathout[,4])))
  
  setTxtProgressBar(pb, j)
  print(paste("Iteration:", k))
  

}
  

print("parameters of the disease onset model (1->2)")
print(onsetout, digits=4)

print("parameters of the death model (1->3)")
print(deathout, digits=4)


# ==========================
# plots of survival curves
# ==========================

par(mfrow=c(2,2))

surv_fit_onset_final <- survfit(mod_onset)
ggsurv_onset_final <- ggsurvplot(surv_fit_onset_final, data = temp,
                           conf.int = TRUE,        
                           pval = TRUE,            
                           risk.table = TRUE,      
                           ggtheme = theme_minimal())  


print(ggsurv_onset_final)

surv_fit_death_final <- survfit(mod_death)
ggsurv_death_final <- ggsurvplot(surv_fit_death_final, data = temp,
                           conf.int = TRUE,        
                           pval = TRUE,            
                           risk.table = TRUE,      
                           ggtheme = theme_minimal())  


print(ggsurv_death_final)

aic_onset_final <- AIC(mod_onset)
aic_death_final <- AIC(mod_death)

aic_table_cox_final <- data.frame(
  Model = c("Onset Model", "Death Model"),
  AIC = c(aic_onset_final, aic_death_final)
)

print(aic_table_cox_initial)
print(aic_table_cox_final)

#############################################################################################
# using flexsurv to fit a parametric model for each m augmented datasets -> average estimates
#############################################################################################

all_fits <- vector(mode = "list", length = m)

for (j in 1:m){
  temp <- schemeA_data
  
  dem_generated <- which(demstatus[,j]==1)
  dem_observed <- as.numeric(temp$patient_id[temp$onset==1])
  dem_to_add <- setdiff(dem_generated, dem_observed)
  
  temp$onset[dem_to_add] <- 1
  temp$onset_age[dem_generated] <- dementage[dem_generated,j]
  
  tmat <- mstate::transMat(x = list(c(2, 3),c(3),c()), names = c("Dementia-free","Dementia", "Death")) 
  data_long <- msprep(data = temp, trans = tmat,
                      time = c(NA, "onset_age", "death_time"),
                      status = c(NA, "onset", "dead"),
                      keep = c("age","cov1", "cov2", "cov3"),
                      id="patient_id")
  
  data_long$Tstart[data_long$trans<3] <- data_long$Tstart[data_long$trans<3] +data_long$age[data_long$trans<3]
  data_long$time <- data_long$Tstop-data_long$Tstart
  
  n_trans <- max(tmat, na.rm = TRUE)
  fits_wei <- vector(mode = "list", length = n_trans)
  for (i in 1:3){
    fits_wei[[i]] <- flexsurvreg(Surv(Tstart, Tstop, status) ~ cov1+cov2+cov3,  
                                 data = subset(data_long, trans == i),
                                 dist = "gompertz")
  }
  all_fits[[j]] <- fits_wei
  
}

n_trans <- 3
param_names <- names(coef(all_fits[[1]][[1]]))  # Assuming parameter names are the same across all models
n_params <- length(param_names)
averaged_params <- matrix(0, nrow = n_trans, ncol = n_params)
cov_matrix <- matrix(0, nrow = length(param_names), ncol = length(param_names))
colnames(averaged_params) <- param_names


for (i in 1:n_trans) {
  for (p in 1:n_params) {
    total_param_value <- 0
    for (j in 1:m) {
      total_param_value <- total_param_value + coef(all_fits[[j]][[i]])[p]
    }
    averaged_params[i, p] <- total_param_value / m
  }
}


cumhaz_gompertz<- function(t, shape, rate) {
  baseline_cum_hazard <- (rate / shape) * (exp(shape * t) - 1)
}


covariances <- vector(mode = "list", length = 3)
hazard_data <- vector(mode = "list", length = 3)


time_points <- seq(60, 102, by = 0.5)


for (i in 1:3) {

  cov_matrix <- matrix(0, nrow = 2, ncol = 2)
  for (j in 1:m) {
    cov_matrix <- cov_matrix + vcov(all_fits[[j]][[i]])[1:2,1:2]
  }
  covariances[[i]] <- cov_matrix / m
}

for (i in 1:3) {

  shape <- averaged_params[i, "shape"]
  rate <- averaged_params[i, "rate"]
  
  se_shape <- sqrt(covariances[[i]]["shape", "shape"])
  se_rate  <- sqrt(covariances[[i]]["rate", "rate"])

  cum_haz <- cumhaz_gompertz(time_points, shape, rate)


  cum_haz_lower <- cumhaz_gompertz(
    time_points,
    shape - 1.96 * se_shape, rate - 1.96 * se_rate)

  cum_haz_upper <- cumhaz_gompertz(
    time_points,
    shape + 1.96 * se_shape, rate + 1.96 * se_rate)


  hazard_data[[i]] <- data.frame(
    time = time_points,
    cumhaz = cum_haz,
    lower = cum_haz_lower,
    upper = cum_haz_upper
  )
}

par(mfrow = c(2, 2))
for (i in 1:2) {
  plot(hazard_data[[i]]$time, hazard_data[[i]]$cumhaz, type = "l", lwd = 2,
       ylim = range(c(hazard_data[[i]]$lower, hazard_data[[i]]$upper)),
       xlim = c(60, 102), xlab = "Age", ylab = "Cumulative Hazard",
       main = paste("Transition", i))

  polygon(c(hazard_data[[i]]$time, rev(hazard_data[[i]]$time)),
          c(hazard_data[[i]]$upper, rev(hazard_data[[i]]$lower)),
          col = rgb(0, 0, 0, 0.1), border = NA)


  lines(hazard_data[[i]]$time, hazard_data[[i]]$lower, lty = 2)
  lines(hazard_data[[i]]$time, hazard_data[[i]]$upper, lty = 2)
}

plot(hazard_data[[3]]$time, hazard_data[[3]]$cumhaz, type = "l", lwd = 2,
     ylim = range(c(hazard_data[[3]]$lower, hazard_data[[3]]$upper)),
     xlim = c(75, 102), xlab = "Age", ylab = "Cumulative Hazard",
     main = paste("Transition", i))

polygon(c(hazard_data[[3]]$time, rev(hazard_data[[3]]$time)),
        c(hazard_data[[3]]$upper, rev(hazard_data[[3]]$lower)),
        col = rgb(0, 0, 0, 0.1), border = NA)


lines(hazard_data[[i]]$time, hazard_data[[i]]$lower, lty = 2)
lines(hazard_data[[i]]$time, hazard_data[[i]]$upper, lty = 2)


# averaged aic over m imputed dataset for 3 models

aic_matrix <- matrix(NA, nrow = m, ncol = 3)
for (i in 1:10) {
  for (j in 1:3) {
    aic_matrix[i, j] <- AIC(all_fits[[i]][[j]])  
  }
}
average_aic <- colMeans(aic_matrix, na.rm = TRUE)

aic_table_imputed <- data.frame(
  Model = c("Transition 1", "Transition 2", "Transition 3"),
  AIC = average_aic
)

# plot parametric model fitted over a random imputed dataset

par(mfrow=c(2,2))
plot(all_fits[[2]][[1]],type="cumhaz", xlim=c(60,102))
plot(all_fits[[2]][[2]],type="cumhaz", xlim=c(60,102))
plot(all_fits[[2]][[3]],type="cumhaz", xlim=c(75,100))
title(main = " Model per transition over Imputed Dataset", outer = TRUE, line=-1)


############################################################################
# using flexsurv to fit a parametric model over averaged m imputed datasets
############################################################################

temp <- schemeA_data

dementage_avg <- rowMeans(dementage)
demstatus_avg <- rowMeans(demstatus)
demstatus_avg <- ifelse(demstatus_avg>=0.3,1,0)
temp$dem <- dementage_avg

dem_generated <- which(demstatus_avg==1)
dem_observed <- as.numeric(temp$patient_id[temp$onset==1])
dem_to_add <- setdiff(dem_generated, dem_observed)

temp$onset[dem_to_add] <- 1
temp$onset_age[dem_generated] <- dementage_avg[dem_generated]

tmat <- mstate::transMat(x = list(c(2, 3),c(3),c()), names = c("Dementia-free","Dementia", "Death")) 
data_long <- msprep(data = temp, trans = tmat,
                    time = c(NA, "onset_age", "death_time"),
                    status = c(NA, "onset", "dead"),
                    keep = c("age","cov1", "cov2", "cov3"),
                    id="patient_id")

data_long$Tstart[data_long$trans<3] <- data_long$Tstart[data_long$trans<3] +data_long$age[data_long$trans<3]
data_long$time <- data_long$Tstop-data_long$Tstart


n_trans <- max(tmat, na.rm = TRUE)
aic_values <- numeric()
fits_wei <- vector(mode = "list", length = n_trans)
for (i in 1:3){
  fits_wei[[i]] <- flexsurvreg(Surv(Tstart, Tstop, status) ~ cov1+cov2+cov3,  
                               data = subset(data_long, trans == i),
                               dist = "gompertz")
}

par(mfrow=c(2,2))
plot(fits_wei[[1]],type="cumhaz", xlim=c(60,102))
plot(fits_wei[[2]],type="cumhaz", xlim=c(60,102))
plot(fits_wei[[3]],type="cumhaz", xlim=c(75,100))
title(main = " Model per transition over averaged imputed datasets", outer = TRUE, line = -1)


for (i in 1:3){
  print(fits_wei[[i]])
  aic_values[i] <- AIC(fits_wei[[i]])
}

params <- matrix(0, nrow = n_trans, ncol = 5)
param_names <- names(fits_wei[[1]]$coefficients)
colnames(params) <- param_names

for (i in 1:3){
  for (j in 1:5){
    params[i,j] <- fits_wei[[i]] $coefficients[j]
  }
}

aic_table <- data.frame(
  Model = c("Transition 1", "Transition 2", "Transition 3"),
  AIC = aic_values
)



############################
# mice
###########################

#install.packages("mice")
library(mice)

schemeA_data <- data[[2]]

for (i in 1:n_pats){
  if(any(schemeA_data$onset[schemeA_data$patient_id==i]==1))
    schemeA_data$onset[schemeA_data$patient_id==i] <- 1
}
schemeA_data <- schemeA_data[,1:9]
schemeA_data <- schemeA_data %>%
  group_by(patient_id) %>%
  slice(1) %>%
  ungroup()

n_Iter <- 100
seeds <- sample(1:10000, size = n_Iter, replace = FALSE)
count_imputed_onset<- numeric(nrow(schemeA_data))
observed_onset <- which(schemeA_data$onset==1)

for (i in 1:n_Iter){
  temp <- schemeA_data
  temp$imputed_onset <- temp$onset
  temp$imputed_onset <- as.factor(temp$imputed_onset)
  rows_to_impute <- which(temp$onset == 0)
  n_to_set_na <- ceiling(0.4 * length(rows_to_impute))
  rows_to_set_na <- sample(rows_to_impute, n_to_set_na) 
  temp$imputed_onset[rows_to_set_na]<- NA
  
  pred <- quickpred(temp)
  pred[10,] <- 1
  pred[10,7] <- 0
  imputed_data <- mice(temp, m = 1, method= "logreg", predictorMatrix = pred, seed = seeds[i])
  
  completed_data <- complete(imputed_data, 1) 
  completed_data$imputed_onset <- as.numeric(as.character(completed_data$imputed_onset))
  imputed_to_1 <- setdiff(which(completed_data$imputed_onset==1),observed_onset)
  count_imputed_onset[imputed_to_1] <- count_imputed_onset[imputed_to_1] + 1
}


count_imputed_onset <- count_imputed_onset/n_Iter
selected <- which(count_imputed_onset>=0.05)
temp$imputed_onset <- temp$onset
temp$imputed_onset <- ifelse(temp$patient_id %in% selected, 1,temp$imputed_onset)
sum(temp$imputed_onset==1)


